language: minimal

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - docker -v && docker-compose -v

install:
  - docker-compose -f docker-compose-build.yaml build --parallel

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-user-api mohit7me/udagram-user-api:latest
  - docker tag udagram-feed-api mohit7me/udagram-feed-api:latest
  - docker tag udagram-reverseproxy mohit7me/udagram-reverseproxy:latest
  - docker tag udagram-react-frontend mohit7me/udagram-react-frontend:latest
  - docker tag udagram-video-api mohit7me/udagram-video-api:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mohit7me/udagram-user-api:latest
  - docker push mohit7me/udagram-feed-api:latest
  - docker push mohit7me/udagram-reverseproxy:latest
  - docker push mohit7me/udagram-react-frontend:latest
  - docker push mohit7me/udagram-video-api:latest
